apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::820201706928:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-194EJI4QO0MFQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::820201706928:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T20:31:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1666"
  uid: 4271460b-7bbd-4e77-ae76-66f47d38824b
